<Project>
  <PropertyGroup>
    <_CoreLibAssemblyName>System.Private.CoreLib.dll</_CoreLibAssemblyName>
    <_PatchedCoreLibDir>$(ArtifactsPath)\patches\$(MSBuildProjectName)</_PatchedCoreLibDir>
    <_PatchedCoreLibPath>$(_PatchedCoreLibDir)\$(_CoreLibAssemblyName)</_PatchedCoreLibPath>
  </PropertyGroup>

  <Target Name="PatchCoreLibFile"
          BeforeTargets="_ResolveWasmOutputs"
          Inputs="@(ReferenceCopyLocalPaths->WithMetadataValue('FileName','System.Private.CoreLib')->WithMetadataValue('Extension','.dll'));$(MSBuildThisFileDirectory)PatchCoreLib.targets.cs"
          Outputs="$(_PatchedCoreLibPath)">
    <ItemGroup>
      <_CoreLibCandidate Include="@(ReferenceCopyLocalPaths)"
                         Condition="'%(ReferenceCopyLocalPaths.FileName)%(ReferenceCopyLocalPaths.Extension)' == '$(_CoreLibAssemblyName)'" />
    </ItemGroup>

    <Error Condition="'@(_CoreLibCandidate)' == ''"
           Text="$(_CoreLibAssemblyName) not found in ReferenceCopyLocalPaths." />

    <MakeDir Directories="$(_PatchedCoreLibDir)" />

    <Exec Command="&quot;$(DOTNET_HOST_PATH)&quot; run --file &quot;$(MSBuildThisFileDirectory)PatchCoreLib.targets.cs&quot; &quot;@(_CoreLibCandidate)&quot; &quot;$(_PatchedCoreLibPath)&quot;" />
  </Target>

  <Target Name="UsePatchedCoreLib"
          BeforeTargets="_ResolveWasmOutputs"
          DependsOnTargets="PatchCoreLibFile">
    <ItemGroup>
      <_CoreLibCandidate Include="@(ReferenceCopyLocalPaths)"
                         Condition="'%(ReferenceCopyLocalPaths.FileName)%(ReferenceCopyLocalPaths.Extension)' == '$(_CoreLibAssemblyName)'" />
    </ItemGroup>

    <Error Condition="'@(_CoreLibCandidate)' == ''"
           Text="$(_CoreLibAssemblyName) not found in ReferenceCopyLocalPaths." />

    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(_CoreLibCandidate)" />
    </ItemGroup>

    <!-- Use `->` to ensure the original metadata are preserved (only the path is replaced). -->
    <ItemGroup>
      <ReferenceCopyLocalPaths Include="@(_CoreLibCandidate->'$(_PatchedCoreLibPath)')" KeepDuplicates="false" />
    </ItemGroup>
  </Target>

  <Target Name="PublishPatchedCoreLib"
          AfterTargets="_ResolveCopyLocalAssetsForPublish"
          DependsOnTargets="PatchCoreLibFile">
    <ItemGroup>
      <_ResolvedCopyLocalPublishAssets Remove="@(_CoreLibCandidate)" />
    </ItemGroup>

    <!-- Use `->` to ensure the original metadata are preserved (only the path is replaced). -->
    <ItemGroup>
      <_ResolvedCopyLocalPublishAssets Include="@(_CoreLibCandidate->'$(_PatchedCoreLibPath)')" KeepDuplicates="false" />
    </ItemGroup>
  </Target>
</Project>
