<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CompressionEnabled>false</CompressionEnabled>
    <TargetFramework>net8.0-browser</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="9.1.0.7988" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.15" IsImplicitlyDefined="true" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.15" PrivateAssets="all" IsImplicitlyDefined="true" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.13.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Features" Version="4.13.0" />
    <PackageReference Include="Mobius.ILasm" Version="0.1.0" />
    <PackageReference Include="System.Security.Permissions" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Runtime" />
    <TrimmerRootAssembly Include="System.Console" />
    <TrimmerRootAssembly Include="System.Text.RegularExpressions" />
    <TrimmerRootAssembly Include="System.Linq" />
    <TrimmerRootAssembly Include="System.Linq.Expressions" />
    <TrimmerRootAssembly Include="System.Net.Primitives" />
    <TrimmerRootAssembly Include="System.Net.Http" />
    <TrimmerRootAssembly Include="System.Private.Uri" />
    <TrimmerRootAssembly Include="System.ComponentModel.Primitives" />
    <TrimmerRootAssembly Include="System.Collections.Concurrent" />
    <TrimmerRootAssembly Include="System.Collections.NonGeneric" />
    <TrimmerRootAssembly Include="Microsoft.CSharp" />
    <TrimmerRootAssembly Include="Microsoft.VisualBasic.Core" />
    <TrimmerRootAssembly Include="System.Net.WebClient" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="GetFrameworkXmlDocumentation" AfterTargets="ResolveReferences">
    <ItemGroup>
      <OutputDocuments Include="@(Reference->'%(RootDir)%(Directory)%(Filename).xml')" Condition="Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <Target Name="CopyAssembliesToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(OutputPath)wwwroot\_framework" />
  </Target>

  <Target Name="CopyAssembliesToPublishDirectory" AfterTargets="CopyFilesToPublishDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(PublishDir)wwwroot\_framework" />
  </Target>

</Project>
