<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CompressionEnabled>false</CompressionEnabled>
    <IsTrimmable>true</IsTrimmable>
    <NoWarn>$(NoWarn);CA1873;VSTHRD103</NoWarn>
    <Nullable>enable</Nullable>
    <PublishTrimmed>false</PublishTrimmed>
    <RunNPMCompilation>true</RunNPMCompilation>
    <TargetFramework>net10.0-browser</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="10.0.0.8330" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.7.0-1.26208.110" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Features" Version="5.7.0-1.26208.110" />
    <PackageReference Include="Mobius.ILasm" Version="0.1.0" />
    <PackageReference Include="System.Security.Permissions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(NetCoreRoot)\sdk\$(NETCoreSdkVersion)\Sdks\Microsoft.NET.Sdk\analyzers\*.dll" Aliases="Analyzers" />
    <Reference Include="$(NetCoreTargetingPackRoot)\Microsoft.NETCore.App.Ref\$(BundledNETCoreAppPackageVersion)\analyzers\dotnet\cs\*.dll" Aliases="AnalyzersCSharp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties\PatchCoreLib.targets.cs" />
    <None Include="Properties\PatchCoreLib.targets.cs" />
  </ItemGroup>

  <Target Name="NPMRestore" AfterTargets="Restore">
    <Exec Command="npm install" WorkingDirectory="Site" />
  </Target>

  <Target Name="NPMBuild" BeforeTargets="PreBuildEvent">
    <PropertyGroup>
      <RunNPMCompilation Condition="$(RunNPMCompilation) == ''">false</RunNPMCompilation>
      <NPMArguments Condition="$(_IsPublishing) == 'true'">$(NPMArguments) --mode publish</NPMArguments>
    </PropertyGroup>
    <ItemGroup Condition="$(_IsPublishing) == 'true'">
      <Content Remove="wwwroot/assets/**/*" />
    </ItemGroup>
    <Exec Command="npm run build -- $(NPMArguments)" WorkingDirectory="Site" Condition="$(RunNPMCompilation)" />
    <ItemGroup Condition="$(_IsPublishing) == 'true'">
      <Content Include="wwwroot/assets/**/*" />
    </ItemGroup>
  </Target>

  <Target Name="GetFrameworkXmlDocumentation" AfterTargets="ResolveReferences">
    <ItemGroup>
      <OutputDocuments Include="@(Reference->'%(RootDir)%(Directory)%(Filename).xml')" Condition="Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <Target Name="CopyDocumentationsToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(OutputPath)wwwroot\_framework" />
  </Target>

  <Target Name="CopyDocumentationsToPublishDirectory" AfterTargets="CopyFilesToPublishDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(PublishDir)wwwroot\_framework" />
  </Target>

  <Import Project="Properties\PatchCoreLib.targets" />

</Project>
