<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CompressionEnabled>false</CompressionEnabled>
    <IsTrimmable>true</IsTrimmable>
    <NoWarn>$(NoWarn);CA1873;VSTHRD103</NoWarn>
    <PublishTrimmed>false</PublishTrimmed>
    <TargetFramework>net10.0-browser</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="10.0.0.8079-preview1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="5.3.0-2.25570.106" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Features" Version="5.3.0-2.25570.106" />
    <PackageReference Include="Mobius.ILasm" Version="0.1.0" />
    <PackageReference Include="System.Security.Permissions" Version="10.0.0" />
  </ItemGroup>

  <Target Name="NPMRestore" AfterTargets="Restore">
    <Exec Command="npm install" WorkingDirectory="Site" />
  </Target>

  <Target Name="NPMBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="npm run build" WorkingDirectory="Site" />
  </Target>

  <Target Name="GetFrameworkXmlDocumentation" AfterTargets="ResolveReferences">
    <ItemGroup>
      <OutputDocuments Include="@(Reference->'%(RootDir)%(Directory)%(Filename).xml')" Condition="Exists('%(RootDir)%(Directory)%(Filename).xml')" />
    </ItemGroup>
  </Target>

  <Target Name="CopyDocumentationsToOutputDirectory" AfterTargets="CopyFilesToOutputDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(OutputPath)wwwroot\_framework" />
  </Target>

  <Target Name="CopyDocumentationsToPublishDirectory" AfterTargets="CopyFilesToPublishDirectory" DependsOnTargets="GetFrameworkXmlDocumentation">
    <Copy SourceFiles="@(OutputDocuments)" DestinationFolder="$(PublishDir)wwwroot\_framework" />
  </Target>

</Project>
